## Problem Statement
Iphone Purchases are getting increased day by day and many stores wants to predict whether a customer will purchase an Iphone 
from thier store given their gender, age and salary.

Prepare a proper Machine Learning Algorithm with proper step by step approach.
1. Exploratory Data Analysis
2. Predictive Model
3. Report of the Dashboard in Tableau


Importing the dataset

In [1]:
## libraries
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
path='C:/Users/devar/Desktop/data set1'

In [3]:
os.chdir(path)

In [4]:
os.listdir()

['cast.csv',
 'Copy of Countif Exercise - 1.xlsx',
 'CORELATION ANALYSIS.csv',
 'Iphone Purchase data.csv',
 'salary and position.csv',
 'SATISTICS.xlsx',
 'Students.csv',
 'Titanic_dataset.csv']

In [5]:
data=pd.read_csv('Iphone Purchase data.csv')
data

Gender  Age  Salary  Purchase Iphone
0      Male   19   19000                0
1      Male   35   20000                0
2    Female   26   43000                0
3    Female   27   57000                0
4      Male   19   76000                0
..      ...  ...     ...              ...
395  Female   46   41000                1
396    Male   51   23000                1
397  Female   50   20000                1
398    Male   36   33000                0
399  Female   49   36000                1

[400 rows x 4 columns]

Data Preprocessing

In [6]:
data.shape

(400, 4)

In [7]:
data.columns

Index(['Gender', 'Age', 'Salary', 'Purchase Iphone'], dtype='object')

In [8]:
## Descriptive stats
data.describe()

Age         Salary  Purchase Iphone
count  400.000000     400.000000       400.000000
mean    37.655000   69742.500000         0.357500
std     10.482877   34096.960282         0.479864
min     18.000000   15000.000000         0.000000
25%     29.750000   43000.000000         0.000000
50%     37.000000   70000.000000         0.000000
75%     46.000000   88000.000000         1.000000
max     60.000000  150000.000000         1.000000

In [9]:
data.info

<bound method DataFrame.info of      Gender  Age  Salary  Purchase Iphone
0      Male   19   19000                0
1      Male   35   20000                0
2    Female   26   43000                0
3    Female   27   57000                0
4      Male   19   76000                0
..      ...  ...     ...              ...
395  Female   46   41000                1
396    Male   51   23000                1
397  Female   50   20000                1
398    Male   36   33000                0
399  Female   49   36000                1

[400 rows x 4 columns]>

In [10]:
## Here Gender in string format so we have to convert string to float value.So replacing male->1 female->0
data['Gender'].replace('Male','1', inplace=True)
data['Gender'].replace('Female','0', inplace=True)

In [11]:
X=data[['Gender','Age','Salary']]
y=data['Purchase Iphone']

In [12]:
X

Gender  Age  Salary
0        1   19   19000
1        1   35   20000
2        0   26   43000
3        0   27   57000
4        1   19   76000
..     ...  ...     ...
395      0   46   41000
396      1   51   23000
397      0   50   20000
398      1   36   33000
399      0   49   36000

[400 rows x 3 columns]

In [13]:
y


0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchase Iphone, Length: 400, dtype: int64

train,test split method

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25)

In [15]:
X_train.shape

(300, 3)

In [16]:
X_test.shape

(100, 3)

Using KNN method

In [17]:
from sklearn.neighbors import KNeighborsClassifier

In [18]:
k=5
knn=KNeighborsClassifier(n_neighbors=k)
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [19]:
## Use standardization method
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

In [20]:
StSc_X = StandardScaler()
X_train = StSc_X.fit_transform(X_train)
X_test = StSc_X.transform(X_test)

In [21]:
X_train

array([[ 1.0270319 ,  0.40261524,  0.49390031],
       [ 1.0270319 , -0.16892059, -0.27122828],
       [ 1.0270319 , -0.07366462,  1.61216517],
       [-0.97367959,  0.68838316, -0.91864477],
       [-0.97367959,  2.11722274,  0.37618822],
       [ 1.0270319 , -0.16892059,  0.14076404],
       [ 1.0270319 , -1.12148031,  0.25847613],
       [-0.97367959,  0.11684733,  1.2590289 ],
       [ 1.0270319 , -1.59776017,  0.46447229],
       [-0.97367959, -0.93096837, -1.56606127],
       [-0.97367959,  0.8788951 , -1.41892116],
       [ 1.0270319 , -1.69301614,  0.43504427],
       [ 1.0270319 , -1.02622434, -1.62491732],
       [ 1.0270319 ,  0.2121033 ,  1.05303274],
       [ 1.0270319 ,  2.21247871, -0.83036071],
       [-0.97367959, -0.54994448, -0.06523212],
       [-0.97367959, -1.31199226, -0.65379257],
       [ 1.0270319 ,  0.8788951 , -0.33008432],
       [ 1.0270319 ,  0.49787121,  0.081908  ],
       [ 1.0270319 , -1.21673628,  0.40561625],
       [-0.97367959,  1.64094288, -1.301

In [22]:
X_test

array([[ 1.0270319 ,  0.02159135,  2.1712976 ],
       [ 1.0270319 , -0.35943253, -1.15406895],
       [ 1.0270319 ,  0.8788951 ,  0.52332834],
       [-0.97367959,  0.78363913, -1.41892116],
       [ 1.0270319 , -0.54994448, -1.53663325],
       [-0.97367959,  2.02196677, -0.9480728 ],
       [ 1.0270319 ,  0.30735927, -0.27122828],
       [-0.97367959, -1.40724823, -1.27178104],
       [-0.97367959, -0.35943253, -1.24235302],
       [-0.97367959,  2.11722274, -0.83036071],
       [ 1.0270319 , -0.26417656,  1.31788495],
       [-0.97367959,  0.02159135,  0.28790415],
       [ 1.0270319 , -0.64520045,  0.28790415],
       [ 1.0270319 ,  1.54568691,  0.05247997],
       [-0.97367959, -1.02622434,  1.40616901],
       [-0.97367959,  1.06940705,  1.87701738],
       [-0.97367959, -1.31199226,  0.3467602 ],
       [ 1.0270319 , -1.69301614, -1.50720523],
       [ 1.0270319 ,  0.30735927, -0.38894037],
       [-0.97367959, -0.16892059, -0.59493652],
       [ 1.0270319 ,  0.2121033 ,  1.523

In [23]:
error_rate = []
for i in range(1,20):
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(X_train,y_train)
    pred_i = knn.predict(X_test)
    error_rate.append(np.mean(pred_i != y_test))

In [24]:
for i in range(1,20):
    print("K = ",i,"Errors = ",error_rate)

K =  1 Errors =  [0.1, 0.15, 0.08, 0.06, 0.07, 0.05, 0.05, 0.05, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.05, 0.05, 0.05, 0.04]
K =  2 Errors =  [0.1, 0.15, 0.08, 0.06, 0.07, 0.05, 0.05, 0.05, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.05, 0.05, 0.05, 0.04]
K =  3 Errors =  [0.1, 0.15, 0.08, 0.06, 0.07, 0.05, 0.05, 0.05, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.05, 0.05, 0.05, 0.04]
K =  4 Errors =  [0.1, 0.15, 0.08, 0.06, 0.07, 0.05, 0.05, 0.05, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.05, 0.05, 0.05, 0.04]
K =  5 Errors =  [0.1, 0.15, 0.08, 0.06, 0.07, 0.05, 0.05, 0.05, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.05, 0.05, 0.05, 0.04]
K =  6 Errors =  [0.1, 0.15, 0.08, 0.06, 0.07, 0.05, 0.05, 0.05, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.05, 0.05, 0.05, 0.04]
K =  7 Errors =  [0.1, 0.15, 0.08, 0.06, 0.07, 0.05, 0.05, 0.05, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.05, 0.05, 0.05, 0.04]
K =  8 Errors =  [0.1, 0.15, 0.08, 0.06, 0.07, 0.05, 0.05, 0.05, 0.04, 0.04, 0.04, 

In [25]:
print("Minimun error :-", min(error_rate), "at K = ",error_rate.index(min(error_rate)))

Minimun error :- 0.04 at K =  8


In [26]:
acc = []
for i in range(1,20):
    neigh = KNeighborsClassifier(n_neighbors=i).fit(X_train,y_train)
    yhat = neigh.predict(X_test)
    acc.append(accuracy_score(y_test,yhat))

In [27]:
acc ## Accuracy is high when k=5

[0.9,
 0.85,
 0.92,
 0.94,
 0.93,
 0.95,
 0.95,
 0.95,
 0.96,
 0.96,
 0.96,
 0.96,
 0.96,
 0.96,
 0.96,
 0.95,
 0.95,
 0.95,
 0.96]

In [28]:
k = 5
knn = KNeighborsClassifier(n_neighbors=k)
knn.fit(X_train,y_train)   #### 75% of the data is trained 

KNeighborsClassifier()

In [29]:
pred = knn.predict(X_test)
pred

array([1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0], dtype=int64)

In [30]:
y_test.values

array([1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0], dtype=int64)

In [31]:
accuracy_score(y_test,pred)  ###for k= 5

0.93